name: Loris Library Build
on: 
  workflow_dispatch:
  #push:
   # branches: 
    #  - master
    #tags:
     # - '*'
jobs:
  build_loris_library_win:
    runs-on: [self-hosted, windows]
    steps:
      - name: Cleanup working directory
        working-directory: ${{ github.workspace }}
        run: del *.* /Q /S
        shell: cmd
      - name: Checkout Loris repository
        uses: actions/checkout@v1
        with:
          ref: 'main'
      - name: Build Loris
        working-directory: ${{ github.workspace }}
        run: build_library.bat
        shell: cmd
      - name: Upload Installer
        uses: actions/upload-artifact@v2
        with:
          name: loris_library_win64
          path: ${{ github.workspace }}/*.zip
  build_loris_library_macos:
    runs-on: [self-hosted, macos]
    steps:
      - name: Cleanup working directory
        run: rm -rf "${{github.workspace}}" 
      - name: Checkout loris repository
        uses: actions/checkout@v1
        with:
          ref: 'main'
      - name: Build Library
        working-directory: ${{ github.workspace }}
        run: sh ./build_library.sh
      - name: Upload Installer
        uses: actions/upload-artifact@v2
        with:
          name: loris_library_macOS
          path: ${{ github.workspace }}/*.zip
